baseURL = "www.intermezzio.github.io"
languageCode = "en-us"
title = "Andrew Mascillaro"
theme = "hugo-whisper-theme"
publishDir = "/docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/experience/about"
    weight = 2

[[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 3

[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

[[menu.main]]
    name = "Github"
    url = "https://github.com/intermezzio"
    weight = 5

[params]
  google_analytics_id=""
  homepage_button_link = '/experience'
  homepage_button_text = 'Learn More'
  homepage_intro = 'Andrew Mascillaro is an engineering student at Olin College of Engineering.'
  homepage_image = 'git-puns.gif'
  homepage_caption = "yes"

  [params.homepage_meta_tags]
    meta_description = "Hugo Whisper is a documentation theme built with Hugo."
    meta_og_title = "Andrew Mascillaro"
    meta_og_type = "website"
    meta_og_url = "https://intermezzio.github.io"
    meta_og_image = "intermezzio_logo.png"
    meta_og_caption = "yes" 
    meta_og_description = "Andrew Mascillaro is an engineering student at Olin College of Engineering."

  [params.logo]
      mobile = "intermezzio_logo.png"
      standard  = "intermezzio_logo.png"
